
package p_Telephone;

import p_Telephone.Telephone;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ket752sbah
 */
public class CreateTelephone extends javax.swing.JFrame {
    
    public String numero;
    //public String numeroRex = "^\\+\\d{3} \\d{3}-?\\d{4}";
    public static final ArrayList<Telephone> listeTel = new ArrayList<>();
    
    CreateTelephone() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 0, 255));
        jPanel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(513, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(213, 100));

        btnCt.setBackground(new java.awt.Color(127, 64, 79));
        btnCt.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCt.setForeground(new java.awt.Color(102, 255, 255));
        btnCt.setText("Créer un téléphone");
        btnCt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        btnCt.setOpaque(true);
        btnCt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCtMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(215, 137, 168));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("3PHONE");
        jLabel1.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telephone.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCt)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnCt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCtMouseClicked
        numero = JOptionPane.showInputDialog(rootPane, "Entrer le numero du Tel", "Création d'un téléphone", JOptionPane.QUESTION_MESSAGE);
        for(Telephone e: listeTel){
            while(e.getNumero().equals(numero)){
                numero = JOptionPane.showInputDialog(rootPane, "Entrer le numero du Tel", "Ce telephone existe ", JOptionPane.WARNING_MESSAGE);
            }
        }
        Telephone tel = new Telephone();
        tel.enregis = false;
        if(numero.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Aucun numero saisi !", "Champ vide", JOptionPane.WARNING_MESSAGE);
        }
        else if(numero.length()==9){

            String cheminFichier = "db_";
            File fichier = new File(cheminFichier+numero+".txt");

            if(!fichier.exists())
            {
                int soi = JOptionPane.showConfirmDialog(rootPane, "Souhaitez-vous enregistrer les données\n(historique des appels et contact) de ce téléphone ? ", "Nouv. Enreg. Téléphone", WIDTH, JOptionPane.QUESTION_MESSAGE);
                if(soi == JOptionPane.YES_OPTION){
                    try {
                        tel.enregis = true;
                        fichier.createNewFile();
                        //tel.sargerAppels(cheminFichier+numero+".txt");
                    } catch (IOException ex) {
                        System.out.println("Erreur lors de la création du fihier"+ex.getMessage());
                    }
                }
            }
            else{
                int soi = JOptionPane.showConfirmDialog(rootPane, "Ce téléphone avait été enregistré,\ncontinuer avec les anciennes données ?", "Continuer Enreg. Téléphone", WIDTH, JOptionPane.QUESTION_MESSAGE);
                if(soi == JOptionPane.YES_OPTION){
                    try {
                        tel.enregis = true;
                        tel.sargerAppels(cheminFichier+numero+".txt");
                        fichier.createNewFile();
                    } catch (IOException ex) {
                        System.out.println("Erreur lors de la création du fihier"+ex.getMessage());
                    }
                }
            }
            tel.setTitle(numero);
            tel.setVisible(true);
            listeTel.add(tel);
        }else{
            JOptionPane.showMessageDialog(rootPane, "La taille du numéro doit ête 9 chiffres", "Champ vide", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.CreateTelephoneCTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.LoCreateTelephonegger(CTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.loggiCreateTelephonegetLogger(CTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.CreateTelephonegger.getLogger(CTelephone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             //</editor-fold>
   }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new CreateTelephone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
